# Generated by Django 5.2.8 on 2025-11-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('director_name', models.CharField(default='Desconocido', max_length=255)),
                ('genre', models.CharField(default='Sin género', max_length=100)),
            ],
        ),
    ]
