# Generated by Django 5.2.11 on 2026-02-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_created_at_movie_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='synopsis',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
